# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: Reactions
# Author: https://www.mc-market.org/members/89497/
# Description: Simple plugin for players to interact with.
# Dependencies:
#   -> MySQL Database
#   -> PLJRApi
#   -> Vault (https://www.spigotmc.org/resources/vault.34315/)
#   -> PlaceholderAPI<Optional> (https://www.spigotmc.org/resources/placeholderapi.6245/)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##################\
# Settings Setup #############################################################\
################## Here, you can enable or disable functions of this plugin. # \
                 #############################################################  \
settings:
  clear-answer: true #-> Should we disable(hide) the message from player, that answered?
  cooldown: 300 #-> How long should we wait between reactions? (In seconds)
  time: 20 #-> How long should we give players to react? (In seconds)
  broadcast-chat: true #-> Should we broadcast reactions in chat?
  broadcast-title: true #-> Should we broadcast reactions in titles?
  broadcast-actionbar: true #-> Should we broadcast reactions in actionbars?
  cache-players: true # Should we save player data in memory? (false = loading on each join)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# Words Setup ######################################################################\
############### Here, you can add or remove words, that will be used in reactions. # \
              ######################################################################  \
words:
  - "growth"
  - "held"
  - "happily"
  - "stuck"
  - "soft"
  - "winter"
  - "grain"
  - "ago"
  - "strike"
  - "reach"
  - "language"
  - "writing"
  - "four"
  - "remember"
  - "independent"
  - "flag"
  - "fight"
#|--------------------------------------------------------------------------------------------------------------------|#