name: Reactions
version: ${project.version}
main: me.pljr.reactions.Reactions
api-version: 1.13
authors: [9hx]
description: Simple plugin for players to interact with.
depend: [PLJRApi]
commands:
  reactions:
    description: Main command for Reactions.
  areactions:
    description: Admin command for Reactions.